import Header from "@/components/Header/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Lexend_Deca } from "next/font/google";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });
const lexend = Lexend_Deca({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <div className="h-screen justify-between ">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
